name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
      - uses: actions/setup-go@v4
        if: env.GIT_DIFF
        with:
          go-version: '1.21'
      - run: make test
        if: env.GIT_DIFF
